exclude: '^docs/conf.py'

repos:

#- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
#  sha: v1.0.0
#  hooks:
#      - id: commitlint
#        stages: [commit-msg]
#        additional_dependencies: ['@commitlint/config-conventional']

#-   repo: https://github.com/pre-commit/mirrors-isort
#    rev: v4.3.17  # Use the revision sha / tag you want to point at
#    hooks:
#    -   id: isort

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.6

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: fix-encoding-pragma
  - id: mixed-line-ending
    args: ['--fix=no']
  - id: flake8
  - id: no-commit-to-branch
    args: [--branch, master]
